name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: makeexamples
      run:
        (cd examples ; make )
    - name: maketests
      run:
        (cd examples ; make tests )
